config/routes.rb
Mittycat::Application.routes.draw do
  
  root :to => 'home#welcome'

  devise_for :admins
  
  match 'mittycat' => 'mittycat/portfolios#index'

  match 'about' => 'home#about'
  match 'portfolio(/:callname)' => 'home#portfolio', :as => 'portfolio'
  match 'blog' => 'home#blog'
  match 'album' => 'home#album'
  match 'link' => 'home#link'
  match 'contact' => 'home#contact'
  match 'loremipsum' =>'home#lorem_ipsum'
  
  namespace :mittycat do 
    root :to => 'home#welcome'
    resources :portfolios do
      member do
        resources :portfolio_images do 
          delete 'delete'
          get 'cropping'
          put 'crop'
          get 'allsizes'
        end
      end
    end
    
    match 'getcallname' => 'home#getcallname'
  end
  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable, :recoverable
         :rememberable, :trackable, :validatable, :timeoutable#, :lockable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
  has_attached_file :linkimg,{
      :storage => 's3',
      :bucket => 'mittycat',
      :s3_credentials => {
        :access_key_id => ENV['S3_KEY'],
        :secret_access_key => ENV['S3_SECRET']
      },
      :path => "/#{Rails.env}_#{ENV['DEV_CODENAME']}/clips/portfolios/:styles/:id/:filename",
      :default_url => '/assets/image_not_available.jpg'
    }
  has_many :portfolio_images
  
  validates_attachment_size :linkimg, :less_than => 200.kilobyte
  validates_presence_of :subject
  validates_presence_of :callname
  validates :callname, :uniqueness => true
  validates_attachment_content_type :linkimg, :content_type => ['image/jpeg', 'image/png', 'image/gif', 'image/jpg']
  validate :file_dimensions, :unless => "errors.any?"
  
  before_save :file_dimensions
  
  def file_dimensions
    tempfile = self.linkimg.queued_for_write[:original]
    
    unless tempfile.nil?
      dimension = Paperclip::Geometry.from_file tempfile
      if dimension.width > 60 || dimension.height > 60
        raise ActiveRecord::RecordNotSaved, 'Width or height must be at least 60px'
      end
    end  
  end
  
  
  # Find record by callname
  def self.find_by_callname(callname)
    self.where(:callname => callname).first
  end
  
  # Finds all records in ordered sequences
  def self.find_all_ordered
    self.order('"order" DESC').all
  end
  
end

app/models/portfolio_image.rb
class PortfolioImage < ActiveRecord::Base
  belongs_to :portfolios
  has_attached_file :attach,
    {
      :styles => { 
        :large => "700x400>", 
        :portfolio_cover => "490x368#", 
        :thumbnail => "490x368>", 
        :tiny => '40x40#'
      },
      :storage => 's3',
      :bucket => 'mittycat',
      :s3_credentials => {
        :access_key_id => ENV['S3_KEY'],
        :secret_access_key => ENV['S3_SECRET']
      },
      :path => "/#{Rails.env}_#{ENV['DEV_CODENAME']}/clips/portfolio_images/:styles/:id/:filename",
      :default_url => '/assets/image_not_available.jpg',
      :processors => [:cropper]
    }
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  after_update :reprocess_image, :if => :cropping?
  
  # Validation rules
  validates_attachment_presence :attach
  validates_attachment_size :attach, :less_than => 1.megabyte
  validates_attachment_content_type :attach, :content_type => ['image/jpeg', 'image/png', 'image/gif', 'image/jpg']
  before_save :get_dimensions
  
  # Determines if the image has been cropped or not
  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end  
  
  # gets the image geometry
  def image_geometry(style = :original)
    @geometry ||= {}
    @geometry[style] ||= Paperclip::Geometry.from_file(attach.url(style))
  end
  
  private
    # Reprocess attachment 
    def reprocess_image
      attach.reprocess!(:thumbnail)
    end
    
    def get_dimensions
      tempfile = self.attach.queued_for_write[:original]
      
      unless tempfile.nil?
        dimension = Paperclip::Geometry.from_file tempfile
        self.attach_width = dimension.width
        self.attach_height = dimension.height
      end
    end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home'
  
  def welcome
  end
  
  def about
  end
  
  def portfolio
    @portfolios = Portfolio.find_all_ordered
    if !params[:callname].presence
      @default_portfolio = Portfolio.first
    else
      @default_portfolio = Portfolio.find_by_callname(params[:callname])
    end
  end
  
  def blog
  end
  
  def contact
  end
  
  def lorem_ipsum
  end
  
end

app/controllers/mittycat/home_controller.rb
require 'common_module'

class Mittycat::HomeController < ApplicationController
  layout 'mittycat'
  include CommonModule
  before_filter :authenticate_admin!
  
  def welcome
  end
  
  def getcallname
    callname = create_callname(params[:text])
    respond_to do |format|
      format.json{ render :json => { :callname => callname } }
    end
  end
  
end

app/controllers/mittycat/portfolio_images_controller.rb
class Mittycat::PortfolioImagesController < ApplicationController
  layout 'layouts/mittycat'
  before_filter :authenticate_admin!
  
  # Shows all attached files  
  def create
    @image = PortfolioImage.create!(params[:portfolio_image])
  rescue ActiveRecord::RecordInvalid => e
    @error = e
  ensure
    respond_to do |format|
      format.js
    end
  end
  
  # Delete portfolio image
  def delete
    @image = PortfolioImage.destroy(params[:portfolio_image_id])
  rescue Exception => e
    @error = e
  ensure
    respond_to do |format|
      format.js
    end
  end
  
  # Image cropping UI
  def cropping
    @image = PortfolioImage.find(params[:portfolio_image_id])
  end
  
  def crop
    @image = PortfolioImage.find(params[:portfolio_image_id])
    @image.update_attributes(params[:portfolio_image])
    
    # redirect back to portfolio page
    redirect_to edit_mittycat_portfolio_path(params[:id])
  end
  
  #shows all sizes of the attachement image
  def allsizes
    @image = PortfolioImage.find(params[:portfolio_image_id])
  end
  
end

app/controllers/mittycat/portfolios_controller.rb
class Mittycat::PortfoliosController < ApplicationController
  layout 'mittycat'
  before_filter :authenticate_admin!
    
  def index
    @portfolios = Portfolio.all
  end 
  
  def new
    @portfolio = Portfolio.new
  end
  
  def create
    @portfolio = Portfolio.create!(params[:portfolio])
    
    flash[:notice] = "Portfolio has been created successfully."
    redirect_to mittycat_portfolios_path
  rescue ActiveRecord::RecordNotSaved => e
    @error = e
    respond_to do |format|
      format.js
    end
  end
  
  def edit
    @portfolio = Portfolio.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = "[Exception] Unable to find record!"
    respond_to do |format|
      format.html{ redirect_to(mittycat_portfolios_path) }
    end
  end
  
  def update
    @portfolio = Portfolio.find(params[:id])
    @portfolio.update_attributes(params[:portfolio])
    @portfolio.save
    
    flash[:notice] = "Portfolio has been updated successfully"
    redirect_to mittycat_portfolios_path
  rescue
    respond_to do |format|
      format.html{ render :text => 'AAAAAAAAAAAAAAAAAAAARGGGGGGGGGGGG' }
    end
  end
  
  def destroy
    @portfolio = Portfolio.destroy(params[:id])
    redirect_to mittycat_portfolios_path
  end
  
  ## Handles attachments


  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # got this code snippet from [http://ianpurton.com/helper-to-display-rails-flash-messages]
  # handles flash message
  def flash_helper
    f_names = [:notice, :warning, :message, :error]
    fl = ''
    for name in f_names
      if flash[name]
        fl = fl + "<div class='flash_#{name} ui-state-error ui-corner-all'>" + "<span class='ui-icon ui-icon-info' style='float: left; margin-right: .3em;'></span>" + "#{flash[name]}</div>"
      end
      flash[name] = nil;
    end
    return fl.html_safe
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mittycat/home_helper.rb
module Mittycat::HomeHelper
end

app/helpers/mittycat/portfolio_images_helper.rb
module Mittycat::PortfolioImagesHelper
end

app/helpers/mittycat/portfolios_helper.rb
module Mittycat::PortfoliosHelper
end

app/views/home/about.html.erb
<style type="text/css">
/* footer margin on this page needs to be fixed */
#footer{
	margin-top: -250px;
}
</style>

<%= image_tag "mitty_about.jpg", :id=>"about_image", :alt=>t("about_mitty") %>

app/views/home/lorem_ipsum.html.erb
<div>
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam dui ipsum, tincidunt eu rutrum ac, gravida vitae lectus. Proin auctor vulputate dapibus. Nulla sed magna eu ligula varius rutrum. Integer vulputate nisl quis mi imperdiet sodales. Nunc eu velit vel erat venenatis imperdiet eget ac arcu. Vestibulum at pellentesque magna. Pellentesque eget lectus odio, scelerisque malesuada nibh. Praesent euismod tellus id quam vestibulum vel rhoncus eros faucibus. Quisque tempus, quam id aliquam suscipit, lorem tortor tristique nibh, eu pellentesque lectus lorem vitae lacus. Curabitur ac lacus dui, sed pretium felis. Aliquam erat volutpat.
</p>
<p>
Nullam scelerisque congue ipsum, sagittis hendrerit lorem vestibulum sit amet. Nullam sodales ornare consectetur. Suspendisse quam quam, ultrices sit amet tristique dapibus, posuere eget felis. Sed tempor hendrerit varius. Suspendisse potenti. Phasellus volutpat varius mauris eu ornare. Vivamus porta pulvinar iaculis. Duis bibendum nunc nec turpis feugiat quis tempor eros cursus. Proin fringilla metus non velit dapibus ac consequat elit cursus.
</p>

<p>
Vivamus vel orci non lorem tempor elementum. In non orci bibendum purus volutpat molestie sit amet eu sem. Morbi aliquam pellentesque ante a convallis. Pellentesque ligula lorem, lacinia ut viverra ac, vehicula in magna. Nulla venenatis venenatis sem, in placerat nisi aliquam et. Aliquam nec est et felis blandit scelerisque id vitae odio. Donec ultrices nisi eget est placerat vulputate eu a velit.
</p>
<p>
Aliquam et urna ipsum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut rhoncus malesuada eros, quis imperdiet sapien varius a. Suspendisse potenti. Sed pulvinar posuere quam id fermentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ornare tortor metus. Phasellus lorem massa, fermentum vitae bibendum eget, consectetur ac dui. Nulla justo massa, feugiat ac tempus eu, interdum vitae dui. Sed adipiscing lorem sit amet nunc ornare dictum. Donec et velit purus. Sed mauris nisl, imperdiet ac molestie vel, varius nec turpis.
</p>
<p>
Phasellus posuere eros at magna consectetur molestie. Aliquam nisi tellus, lacinia quis commodo quis, placerat quis libero. Sed ornare ullamcorper sem, fringilla iaculis ante ullamcorper eget. Donec vestibulum rutrum laoreet. Cras sem nulla, ultricies nec tincidunt eu, sodales sit amet nibh. Donec id velit dolor, et pharetra justo. Curabitur nec ipsum justo, non lobortis odio. Nunc quis dolor quam. Praesent nisi nulla, sollicitudin ut elementum et, tincidunt et eros. Maecenas consectetur lacinia quam, eget eleifend leo ornare sed. Sed interdum tincidunt ultricies. Morbi vel elit at odio ultrices elementum. Maecenas ullamcorper, purus id posuere vehicula, nunc erat vestibulum elit, bibendum vehicula turpis arcu eu mi.
</p>
<p>
Suspendisse potenti. Mauris risus purus, gravida ut consectetur eget, tincidunt a ante. Suspendisse facilisis ornare malesuada. Sed vulputate ultricies lacus id auctor. Ut dapibus cursus dapibus. Ut venenatis, eros vitae auctor commodo, leo sapien facilisis enim, quis interdum mi ligula sit amet orci. Sed a ipsum odio. Mauris at neque augue, eget pellentesque diam.
</p>
<p>
Vivamus sagittis eleifend nunc ut hendrerit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla fringilla faucibus elementum. Vestibulum velit est, pharetra bibendum pulvinar semper, hendrerit nec diam. Praesent eu libero lorem, a blandit odio. Proin sed nulla sit amet orci elementum consequat. Etiam urna tellus, sodales ut blandit interdum, fermentum et tellus. Nullam consequat dignissim volutpat. Praesent eleifend facilisis consequat. Maecenas viverra malesuada tellus, eget molestie sapien accumsan a.
</p>
<p>
Mauris eu ante non est suscipit porta. Vivamus volutpat fermentum placerat. Praesent sit amet lorem dui. Integer quis blandit lacus. Quisque accumsan vestibulum diam non auctor. Curabitur faucibus fringilla dui ac dignissim. Aliquam sit amet sapien tellus. Vivamus egestas laoreet egestas.
</p>
</div>

app/views/home/portfolio.html.erb
<div id="portfolio_leftnav"	>
	<div id="title_portfolio" class="title">
		<!-- portfolio title -->
	</div>
	<div class="horiz_navigation">
		<ul>
			<% @portfolios.each do |p| %>
				<% if !@default_portfolio.nil? && @default_portfolio.id == p.id %>
				<li id="<%= p.callname %>"><%= link_to image_tag(p.linkimg.url(:original)),
					portfolio_path(:callname=>p.callname), :class => 'current callname' %></li>
				<% else %>
				<li id="<%= p.callname %>"><%= link_to image_tag(p.linkimg.url(:original)),
					portfolio_path(:callname=>p.callname), :class => 'callname' %></li>
				<% end %>
			<% end unless @portfolios.nil? %>
		</ul>
		<!-- horizontal navigation -->
	</div>
	<div class="thumbnails">
		<div class="top"></div>
		<div class="content">
			<div class="thumbs">
				<ul>
				<% @default_portfolio.portfolio_images.each do |pi|  %>
				  <li dir="<%= "#{pi.attach_width}x#{pi.attach_height}" %>">
					<a id="athumb-<%= pi.id %>"><%= image_tag(pi.attach.url(:thumbnail), 
					:class => 'thumbnail ' + ((@default_portfolio.portfolio_images.first.id == pi.id) ? 'current' : ''), 
					:id => "thumb-#{pi.id}", 
					:dir => pi.attach.url(:original),
					:width => '42px', :height=>'42px') %></a>
				  </li>
				<% end unless @default_portfolio.nil? %>
				</ul>
				<div class="clear">&nbsp;</div>
			</div>
		</div>
		<div class="bottom">
			<%= link_to "", {}, :class=>'link_prev', :alt=>'prev' %>
			<%= link_to "", {}, :class=>'link_next', :alt=>'next' %>
		</div>
	</div>
</div>

<div id="portfolio_content">
	<div class="mushrooms"></div>
	<div class="top"></div>
	<div id="album_cover" class="content">
		<div id="portfolio_holder" class="scroll-pane">
			<% begin %>
			<%= image_tag @default_portfolio.portfolio_images.first.attach.url %>
			<% rescue %>
			<% end %>
		</div>
	</div>
	<div class="bottom"></div>
</div>

app/views/home/welcome.html.erb
<h1>Weclome!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
		"http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
  <title><%= t('page.page_title') %></title>
  <!-- styles -->
  <%= stylesheet_link_tag    "application" %>
  <%= stylesheet_link_tag    params[:controller] %>
  <!--[if IE 6]><%= stylesheet_link_tag 'ie6' %><![endif]-->
  <!--[if IE 7]><%= stylesheet_link_tag 'ie7' %><![endif]-->

  <!-- javascriptes -->
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag params[:controller] %> 

  <%= csrf_meta_tags %>
  <!-- page specific -->
  <%= yield :page_head %>
  <% if params[:debug].nil? %>
	<script type="text/javascript">
		$(document).ready(function(){
		});
	</script>
  <% end %>
</head>
<body>
	<div id="base">
	  <%= render 'shared/globalnav' %>
	  <div id="content">
		  <div class="body">
		  <%= flash_helper %>
		  <%= content_for?(:main) ? yield(:main) : yield %>
		  </div>
	  </div>
	</div>
	
	<div id="footer">
		<div class="cloud"></div>
	</div>
</body>
</html>

app/views/layouts/home.html.erb
<% content_for :main do %>
	<div id='home_<%= params[:action] %>' clcass="home_action">
		<%= yield %>
	</div>
<% end %>

<%= render :file => 'layouts/application' %>

app/views/layouts/mittycat.html.erb
<% content_for :page_head do %>
	<%= stylesheet_link_tag "form" %>
	<%= stylesheet_link_tag "mittycat" %>
<% end %>

<% content_for :main do %>
	<ul id="admin_nav">
		<li><%= link_to 'manage portfolio', mittycat_portfolios_path, :class=>'n_portfolio' %></li>
	</ul>
	<div class="clear">&nbsp;</div>
	<%= yield %>
<% end %>

<%= render :file => 'layouts/application' %>

app/views/mittycat/home/welcome.html.erb
<h1>Welcome</h1>

app/views/mittycat/portfolio_images/allsizes.html.erb
Tiny<br />
<%= image_tag @image.attach.url(:tiny) %><br />
Thumbnail<br />
<%= image_tag @image.attach.url(:thumbnail) %><br />
Portfolio Cover<br />
<%= image_tag @image.attach.url(:portfolio_cover) %><br />
Large<br />
<%= image_tag @image.attach.url(:large) %><br />
Original<br />
<%= image_tag @image.attach.url(:original) %><br />

app/views/mittycat/portfolio_images/create.js.erb
<%= remotipart_response do %>  
    $('#lbl_submit_replacement').fadeOut('fast', function(){
		$('#btn_upload_image').fadeIn('fast', function(){
		  $('#lbl_submit_replacement').hide();
		});
	});
	
  <% if @error.nil? %>
	var img = $('<%= escape_javascript(render(:partial=>'mittycat/portfolios/portfolio_image', :object=>@image)) %>');
	img.hide();
	$('#images').append(img);
	img.fadeIn('fast');
	$('#portfolio_image_attach').val('');
  <% else %>    
	alert('<%=@error.message%>');
  <% end %>
  
<% end %>

app/views/mittycat/portfolio_images/cropping.html.erb
<% content_for :page_head do %>
  <%= stylesheet_link_tag 'jquery.Jcrop' %>
  <%= javascript_include_tag 'jquery.color' %>
  <%= javascript_include_tag 'jquery.Jcrop.min' %>
<% end %>

<%= hidden_field_tag 'large_width', @image.image_geometry(:large).width %>
<%= hidden_field_tag 'large_height', @image.image_geometry(:large).height %>

<%= hidden_field_tag 'original_width', @image.image_geometry.width %>
<%= hidden_field_tag 'original_height', @image.image_geometry.height %>


<%= image_tag @image.attach.url(:large), :id => "cropbox" %>

<h4>Preview:</h4>
<div style="width:75px; height:75px; overflow:hidden">
  <%= image_tag @image.attach.url(:large), :id => "preview" %>
</div>
<hr />
<%= semantic_form_for([:mittycat, @image],
      :url => mittycat_portfolio_image_crop_path(:portfolio_id => params[:id], :portfolio_image_id=>@image.id),
      :method => :PUT,
      :html => { :class=> 'form', :id=>'editform' }
     ) do |f| %>
  <% for attribute in [:crop_x, :crop_y, :crop_w, :crop_h] %>
    <%= f.text_field attribute, :id => attribute %>
  <% end %>
  <p><%= f.submit "Crop" %></p>
<% end %>

app/views/mittycat/portfolio_images/delete.js.erb
<% if !@image.nil? && @error.nil? %>
$('#image_<%=@image.id%>').fadeOut('fast');
<% else %>
alert('Failed to delete image: <%=@error.message%>');
<% end %>

app/views/mittycat/portfolios/_form.html.erb
<% if @portfolio.errors.any? %>
	<div id="error_description">
		<h2><%= pluralize(@portfolio.errors.count, "error") %>
			@prohibited this comment from being saved:</h2>
		<ul>
			<% @portfolio.errors.each do |err| %>
				<li><%= err %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<ul class="form">
	<li>
		<%= f.label t('.l_subject'), :class => 'required desc' %>
		<%= f.text_field :subject, :value => @portfolio.subject %>
	</li>
	<li>
		<%= f.label t('.l_callname'), :class => 'required desc' %>
		<%= f.text_field :callname, :value => @portfolio.callname %>
	</li>
	<li>
		<%= f.label t('.l_linkimg'), :class => 'desc' %>
		<%= f.file_field :linkimg %>
		<div class="image-port">
			<%= image_tag @portfolio.linkimg.url %>
		</div>
	</li>
	<li>
		<%= hidden_field_tag "get_callname_path", mittycat_getcallname_path %>
		<%= f.label t('.l_description'), :class => 'desc' %>
		<%= f.text_area :description, :cols => 45, :rows => 5, 
				:value => @portfolio.description, :class => 'textarea' %>
	</li>
</ul>

app/views/mittycat/portfolios/_portfolio_image.html.erb
<li class="image" id="image_<%=portfolio_image.id%>">
  <%= link_to image_tag(portfolio_image.attach.url(:thumbnail)), portfolio_image.attach.url(:original), :target => '_blank' %>
  <%= link_to "", mittycat_portfolio_image_delete_path(:portfolio_image_id => portfolio_image.id ), :method => :DELETE, :remote => true, :confirm => 'are you sure?', :class => 'x' %>
  <%= link_to "", mittycat_portfolio_image_cropping_path(:portfolio_image_id => portfolio_image.id), :class => 'crop' %>
  <%= link_to "all sizes", mittycat_portfolio_image_allsizes_path(:portfolio_image_id => portfolio_image.id), :target => '_blank' %>
</li>

app/views/mittycat/portfolios/_portfolio_images.html.erb
<div class="portfolio_images">
  <%= semantic_form_for([:mittycat, PortfolioImage.new(:portfolio_id => portfolio.id)], 
	:remote => true, :validate => true, :method => :POST,
 	:html => { :multipart => true, :class => 'form', :id=>'editform' } ) do |f| %>
  <%= f.hidden_field :portfolio_id, :value=>portfolio.id %>
  <ul class="form">
	<li>
		<%= f.label t('.l_attach_image'), :class => 'required desc' %>
		<%= f.file_field :attach %>
	</li>
	<li>
		<%= f.submit t('.b_submit'), :class=>'submit', :id=>'btn_upload_image'%>
		<label style="display: none;" id="lbl_submit_replacement">Uploading...</label>
	</li>
  </ul>
  <% end %>
 </ul>
 <div class="clear">&nbsp;</div>
  <!-- list of images -->
  <ul id="images">
  <% portfolio_images.each do |image| %>
    <%= render :partial=>'portfolio_image', :object=>image %>
  <% end unless portfolio_images.nil? %>
  </ul>
</div>

app/views/mittycat/portfolios/edit.html.erb
<h2><%= t('.form_title')%></h2>
<%= semantic_form_for([:mittycat, @portfolio], 
	:validate => true, :method => :PUT,
 	:html => { :multipart => true, :class => 'form', :id=>'editform' } ) do |f| %>

	<%= render :partial => 'form', :locals => {:f => f} %>
	<ul class="form">
		<li>
			<%= f.submit t('.b_submit'), :class => 'submit' %>
		</li>
	</ul>
	<div class="spacer">&nbsp;</div>
<% end %>

<!-- show images -->
<div class="portfolio_images_panel">
	<%= render :partial => 'portfolio_images', 
		:object => @portfolio.portfolio_images, :locals => {:portfolio => @portfolio} %>
	<div class="spacer">&nbsp;</div>
</div>

app/views/mittycat/portfolios/index.html.erb
<h2>Portfolios</h2>
<%= link_to "new portfolio", new_mittycat_portfolio_path, :class=>'button' %>
<table>
	<thead>
		<tr>
			<td><%= t('.th_subject') %></td>
			<td><%= t('.th_description')%></td>
			<td><%= t('.th_order') %></td>
			<td><%= t('.th_linkimg') %></td>
			<td>&nbsp;</td>
		</tr>
	</thead>
	<tbody>
	<% @portfolios.each do |p| %>
		<tr>
			<td><%= p.subject %></td>
			<td><%= p.description %></td>
			<td><%= p.order %></td>
			<td><%= image_tag p.linkimg.url %></td>
			<td>
				<%= link_to "edit", edit_mittycat_portfolio_path(p), :class=>'button btn_linkto' %>
				<%= link_to "delete", mittycat_portfolio_path(p), :remote => true,
						:method => :delete, :class=>'button btn_linkto', :confirm => t('.cfm_delete_portfolio') %>
			</td>
		</tr>
	<% end %>
	</tbody>
</table>

app/views/mittycat/portfolios/new.html.erb
<h2><%= t('.form_title')%></h2>
<%= semantic_form_for([:mittycat, Portfolio.new], 
	:validate => true, :method => :POST,
 	:html => { :multipart => true, :class => 'form' } ) do |f| %>

	<%= render :partial => 'form', :locals => {:f => f} %>
	<ul class="form">
		<li>
			<%= f.submit t('.b_submit'), :class => 'submit' %>
		</li>
	</ul>
<% end %>

app/views/shared/_globalnav.html.erb
<script type="text/javascript">
	$(document).ready(function(){
		$('.nlink').html('');		
	});
</script>

<div id="globalnav">
	<ul>
		<li><%= link_to 'home', root_path, :class=>'nlink home' %></li>
		<li><%= link_to 'about', about_path, :class=>'nlink about' %></li>
		<li><%= link_to 'portfolios', portfolio_path, :class => 'nlink portfolio'%></li>
		<li><%= link_to 'blog', blog_path, :class => 'nlink blog'  %></li>
		<li><%= link_to 'album', album_path, :class => 'nlink album'  %></li>
		<li><%= link_to 'link', link_path, :class => 'nlink link'  %></li>
		<li><%= link_to 'contact', contact_path, :class => 'nlink contact'  %></li>
	</ul>
</div>
<div id="navfoot">
	<div class="leftbird"></div>
	<div class="rightswing"></div>
</div>